apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen {{ .Values.service.port }};

      location = /healthz {
        access_log off;
        return 200 'ok';
      }

      location / {
        default_type application/json;
        return 200 '{"service":"backend","message":"hello from the backend"}';
      }
    }
